### ISSUE TITLE
I'd like to use on chrome OS

### ISSUE THREAD

**Issue by Og-Amayokoy** [google/mozc-devices#26]
When is support chrome os?

**Comment by tushuhei** [comment]
Hi there,
Thank you for reaching out to us. This repository is a collection of several devices related to Which device you would like to use on Chrome OS?

**Comment by Yokoyama-Go** [comment]
Google input [Tegaki](https://landing.google.co.jp/tegaki/) is.
I'd like to use tablet mode too.

My device is Chrombook Asus c 101pa. Version 72.0.3626.30 (Official Build) dev (32-bit)

**Comment by makotoshimazu** [comment]
Thanks for reaching out to us. 
The [demo](https://landing.google.co.jp/tegaki/#demo) is working well on my Chromebook. What did you try on your Chromebook?

**Comment by Yokoyama-Go** [comment]
I'm afraid but, I would like to use on usual input like this GitHub issue page, google search box.
Could you develop and make available Google Tegaki input on [Google input tools extension](https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab?utm_source=chrome-app-launcher-search)?

**Comment by makotoshimazu** [comment]
So sorry for my very slow response. I completely missed your response.

Thanks for asking, but actually, Physica Handwriting Version is one of our product release for **the event on April 1st**. We don't have any furthur plans except for the demo.
