### ISSUE TITLE
Gboard 湯呑みバージョンについて

### ISSUE THREAD

**Issue by edama2** [google/mozc-devices#33]
USB-C connector breakoutはどこに接続するんでしょうか？
湯呑みの外装パーツと動画に出てくる専用茶托ドックは3Dデータで公開されるのでしょうか？

**Comment by ikeji** [comment]
外装ではないのですが、promicroバージョンでおつかいいただける高台を公開しました。
https://github.com/google/mozc-devices/blob/master/mozc-yunomi/platform_promicro.stl
