### ISSUE TITLE
ケースの3Dモデルに基板のモデルが混在している

### ISSUE THREAD

**Issue by sthairno** [google/mozc-devices#43]
mozc-barのケースのうち、TypeDのSTLファイルにのみ基板のモデルが混ざっています。

https://github.com/google/mozc-devices/blob/41ac20b478abf2290628bdd20b6066d89c77b12e/mozc-bar/case/typeD.stl

![image](https://user-images.githubusercontent.com/45668272/194700406-631ae7d9-f017-48db-9483-4e6386bb2d70.png)

**Comment by yamaguchi-am** [comment]
ご報告いただき、ありがとうございます。
commit 0e098eb にて修正しました。
