### ISSUE TITLE
Gboard 棒バージョンのPCBとCASE準備数量及びアルミフレーム寸法ミスについて。

### ISSUE THREAD

**Issue by Sakoda1066** [google/mozc-devices#46]
README.mdのPCB及びcaseの準備数が、キーマッピングと一致せず、typeAを9個、typeBを2個準備するよう書かれていますが、正しくはtypeAを8個、typeBを3個だと思います。また、準備するアルミフレーム寸法も間違えた個数に準拠した寸法となっているため、キーマッピング通り組み立てると(typeA幅-typeB幅=76mm?)長いです。

**Comment by ikeji** [comment]
修正しました。ご指摘感謝致します。
